site_name: Data Engineering Knowledge Base
site_url: https://vedanthv.github.io/data-engg-docs/
site_description: "Comprehensive Data Engineering Notes, Tutorials, and Guides by Vedanth"
site_author: "Vedanth V Baliga"

docs_dir: internals-docs-code

extra_css:
  - assets/extra.css

theme:
  name: material
  favicon: assets/images/favicon.ico
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.expand
    - navigation.tracking  
    - search.suggest
    - search.highlight
    - search.share
    - search.index
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - content.code.expand
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - toc:
      permalink: "üîó"
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

# BEGIN AUTO NAV
nav:
  - Home: index.md
  - Azure:
      - Index: azure/index.md
      - Topics:
          - Azure Integration Databricks: azure/00-Azure_Integration_Databricks.md
          - Azure Portal Subscriptions Resourcegroups: azure/01-Azure_Portal_Subscriptions_ResourceGroups.md
          - Azure Cli Scenarios: azure/02-Azure_CLI_Scenarios.md
          - Azure Powershell Scenarios: azure/03-Azure_Powershell_Scenarios.md
          - Azure Arm Templates: azure/05-Azure_ARM_Templates.md
          - Azure Bicep Templates: azure/06-Azure_Bicep_Templates.md
          - Overview Of Azure Storage: azure/07-Overview_Of_Azure_Storage.md
          - Blob Storage Fundamentals: azure/08-Blob_Storage_Fundamentals.md
          - Adls Gen2 Overview: azure/09-ADLS_Gen2_Overview.md
          - Azure Rbac Acl: azure/10-Azure_RBAC_ACL.md
          - Azure Types Of Storage: azure/11-Azure_Types_Of_Storage.md
          - Azure Storage Replication Strategies: azure/12-Azure_Storage_Replication_Strategies.md
          - Soft Delete Pitr Azure Storage: azure/13-Soft_Delete_PITR_Azure_Storage.md
          - Azure Shared Access Signature: azure/14-Azure_Shared_Access_Signature.md
          - Azure Lifetime Management Policies: azure/15-Azure_Lifetime_Management_Policies.md
          - Eventgrid Integration Azure: azure/16-EventGrid_Integration_Azure.md
          - Azure Encrpytion Standards: azure/17-Azure_Encrpytion_Standards.md
          - Azure+ Private Endpoints: azure/18-Azure+_Private_Endpoints.md
          - Cross Region Replication Azure: azure/19-Cross_Region_Replication_Azure.md
          - Azure Storage Rest Api: azure/20-Azure_Storage_Rest_API.md
          - Introduction Azure Data Factory: azure/21-Introduction_Azure_Data_Factory.md
          - Azure Data Factory Vs Synapse: azure/22-Azure_Data_Factory_vs_Synapse.md
          - Azure Data Factory Architecture: azure/23-Azure_Data_Factory_Architecture.md
          - Azure Data Factory Triggers : azure/24-ADF_Triggers_Intro.md
          - Azure Data Factory Parameters : azure/25-ADF_Parameters.md
  - Data Formats:
      - Index: data-formats/index.md
      - Topics:
          - Data Format Deep Dive Pt1: data-formats/01-Data_Format_Deep_Dive_Pt1.md
          - Parquet Format Internals: data-formats/02-Parquet_Format_Internals.md
  - Databricks:
      - Index: databricks/index.md
      - Topics:
          - Azure Databricks Uc Creation: databricks/01-Azure_Databricks_UC_Creation.md
          - Databricks Uc Introduction: databricks/02-Databricks_UC_Introduction.md
          - Databricks Managed External Tables Hive: databricks/03-Databricks_Managed_External_Tables_Hive.md
          - Uc External Location Storage Credentials: databricks/04-UC_External_Location_Storage_Credentials.md
          - Databricks Managed Location Catalog Schema Level: databricks/05-Databricks_Managed_Location_Catalog_Schema_Level.md
          - Ctas Deep Clone Shallow Clone Databricks: databricks/06-CTAS_Deep_Clone_Shallow_Clone_Databricks.md
          - Rbac Custom Roles Serviceprincipals: databricks/07-RBAC_Custom_Roles_ServicePrincipals.md
          - Deletion Vectors Delta Lake: databricks/08-Deletion_Vectors_Delta_lake.md
          - Liquid Clustering Delta Lake: databricks/09-Liquid_Clustering_Delta_Lake.md
          - Concurrency Liquid Clustering: databricks/10-Concurrency_Liquid_Clustering.md
          - Copy Into Databricks: databricks/11-Copy_Into_Databricks.md
          - Autoloader Databricks: databricks/12-AutoLoader_Databricks.md
          - Autoloader Schema Inference and Evolution: databricks/12.1-AutoLoader_Databricks_Schema_Inference.md
          - Intro Databricks Lakeflow Declarative Pipelines: databricks/13-Intro_Databricks_Lakeflow_Declarative_Pipelines.md
          - Dlt Batch Vs Streaming Workloads: databricks/14-DLT_Batch_Vs_Streaming_Workloads.md
          - Dlt Data Storage Checkpoints: databricks/15-DLT_Data_Storage_Checkpoints.md
          - Databricks Secret Scopes: databricks/16-Databricks_Secret_Scopes.md
          - Databricks Controlplane Dataplane: databricks/17-Databricks_ControlPlane_DataPlane.md
          - Databricks Dlt Code Walkthrough: databricks/18-Databricks_DLT_Code_Walkthrough.md
          - Databricks Serverless Compute: databricks/19-Databricks_Serverless_Compute.md
          - Databricks Warehouses: databricks/20-Databricks_Warehouses.md
          - Databricks Lakehouse Federation: databricks/21-Databricks_Lakehouse_Federation.md
          - Databricks Metrics Views: databricks/22-Databricks_Metrics_Views.md
          - Databricks Streaming Materialized Views Sql: databricks/23-Databricks_Streaming_Materialized_Views_SQL.md
          - Databricks Cli Setup: databricks/24-Databricks_CLI_Setup.md
  - Scenarios:
      - Index: scenarios/index.md
      - Topics:
          - Spark:
              - Index: scenarios/spark/index.md
              - Topics:
                  - Smj Spill To Disk Q1: scenarios/spark/01-SMJ_Spill_To_Disk_Q1.md
                  - Smj Spill To Disk Q2: scenarios/spark/02-SMJ_Spill_To_Disk_Q2.md
                  - Smj Output During Spill Q3: scenarios/spark/03-SMJ_Output_During_Spill_Q3.md
                  - Cross Vs Broadcast Join: scenarios/spark/04-Cross_vs_Broadcast_Join.md
          - Databricks:
              - Index: scenarios/databricks/index.md
              - Topics:
                  - AWS Reference Architecture and Integration with Databricks: scenarios/databricks/00-AWS_Reference_Arch_Databricks.md
                  - AWS + Databricks Reference Architecture: scenarios/databricks/01-Reference_Architectures_Pt1.md
          - Kafka:
              - Index: scenarios/kafka/index.md
              - Topics:
                  - Why are closed segment files kept open by Kafka: scenarios/kafka/00-Why_Closed_Segments_Files_Open.md
                  - How does producer guranteee exactly once semantics: scenarios/kafka/01-How_Does_Producer_Guarantee_Exactly_Once.md
                  - Does sequence number remain the same after producer goes down?: scenarios/kafka/02-Does_Seq_No_Remain_Same_After_Producer_Goes_Down.md
                  - What is the scenario when relection happens and how is idempotency ensured?: scenarios/kafka/03-What_Happens_When_ReElection_Happens.md
                  - Give me a walkthrough of leader epochs and their role in log truncation: scenarios/kafka/04-Give_Walkthrough_Of_Leader_Epoch_Log_Truncation.md
  - Spark:
      - Index: spark/index.md
      - Topics:
          - Spark Architecture Yarn: spark/01-Spark_Architecture_YARN.md
          - Spark Driver Oom: spark/02-Spark_Driver_OOM.md
          - Types Of Memory Spark: spark/03-Types_Of_Memory_Spark.md
          - Spark Dynamic Partition Pruning: spark/04-Spark_Dynamic_Partition_Pruning.md
          - Spark Salting Technique: spark/05-Spark_Salting_Technique.md
          - What Is Spark: spark/06-What_Is_Spark.md
          - Why Apache Spark: spark/07-Why_Apache_Spark.md
          - Hadoop Vs Spark: spark/08-Hadoop_Vs_Spark.md
          - Spark Ecosystem: spark/09-Spark_Ecosystem.md
          - Spark Ecosystem: spark/10-Spark_Ecosystem.md
          - Spark Architecture: spark/11-Spark_Architecture.md
          - Schema In Spark: spark/12-Schema_In_Spark.md
          - Handling Corrupt Records Spark: spark/13-Handling_Corrupt_Records_Spark.md
          - Spark Transformations Actions: spark/14-Spark_Transformations_Actions.md
          - Spark Dag Lazy Eval: spark/15-Spark_DAG_Lazy_Eval.md
          - Spark Json Data: spark/16-Spark_JSON_Data.md
          - Spark Sql Engine: spark/17-Spark_SQL_Engine.md
          - Spark Rdd: spark/18-Spark_RDD.md
          - Spark Writing Data Disk: spark/19-Spark_Writing_Data_Disk.md
          - Spark Partitioning Bucketing: spark/20-Spark_Partitioning_Bucketing.md
          - Spark Session Vs Context: spark/21-Spark_Session_vs_Context.md
          - Spark Job Stage Task: spark/22-Spark_Job_Stage_Task.md
          - Spark Transformations: spark/23-Spark_Transformations.md
          - Spark Union Vs Unionall: spark/24-Spark_Union_vs_UnionAll.md
          - Spark Repartition Vs Coalesce: spark/25-Spark_Repartition_vs_Coalesce.md
          - Spark Case When: spark/26-Spark_Case_When.md
          - Spark Unique Sorted Records: spark/27-Spark_Unique_Sorted_Records.md
          - Spark Agg Functions: spark/28-Spark_Agg_Functions.md
          - Spark Group By: spark/30-Spark_Group_By.md
          - Spark Joins Intro: spark/31-Spark_Joins_Intro.md
          - Spark Join Strategies: spark/32-Spark_Join_Strategies.md
          - Spark Window Functions: spark/33-Spark_Window_Functions.md
          - Spark Memory Management: spark/34-Spark_Memory_Management.md
          - Spark Executor Oom: spark/35-Spark_Executor_OOM.md
          - Spark Submit Command: spark/36-Spark_Submit_Command.md
          - Spark Deployment Modes: spark/37-Spark_Deployment_Modes.md
          - Spark Adaptive Query Execution: spark/38-Spark_Adaptive_Query_Execution.md
          - Spark Dynamic Resource Allocation: spark/39-Spark_Dynamic_Resource_Allocation.md
          - Spark Dynamic Partition Pruning: spark/40-Spark_Dynamic_Partition_Pruning.md
  - Streaming:
      - Index: streaming/index.md
      - Topics:
          - Architecture:
              - Index: streaming/architecture/index.md
              - Topics:
                  - Use Cases Streaming: streaming/architecture/01-Use_Cases_Streaming.md
                  - Redpanda Vs Kafka Arch Differences: streaming/architecture/02-Redpanda_vs_Kafka_Arch_Differences.md
                  - Redpanda Architure In Depth Pt1: streaming/architecture/03-Redpanda_Architure_In_Depth_Pt1.md
          - Kafka:
              - Index: streaming/kafka/index.md
              - Topics:
                  - Kafka Kraft Setup: streaming/kafka/01-Kafka_KRaft_Setup.md
                  - Kafka Broker Properties: streaming/kafka/02-Kafka_Broker_Properties.md
                  - Topic Default Properties: streaming/kafka/03-Topic_Default_Properties.md
                  - Kafka Hardware Considerations: streaming/kafka/04-Kafka_Hardware_Considerations.md
                  - Kafka Configuring Clusters Broker Consideration: streaming/kafka/05-Kafka_Configuring_Clusters_Broker_Consideration.md
                  - Kafka Broker Os Tuning: streaming/kafka/06-Kafka_Broker_OS_Tuning.md
                  - Kafka Os Tuning Dirty Page Handling: streaming/kafka/07-Kafka_OS_Tuning_Dirty_Page_Handling.md
                  - Kafka File Descriptors Overcommit Memory: streaming/kafka/08-Kafka_File_Descriptors_Overcommit_Memory.md
                  - Kafka Production Concerns: streaming/kafka/09-Kafka_Production_Concerns.md
                  - Kafka Message Types: streaming/kafka/10-Kafka_Message_Types.md
                  - Kafka Configuring Producers Pt1: streaming/kafka/11-Kafka_Configuring_Producers_Pt1.md
                  - Kafka Configuring Producers Pt2: streaming/kafka/12-Kafka_Configuring_Producers_Pt2.md
                  - Kafka File Descriptors Overcommit Memory: streaming/kafka/08-Kafka_File_Descriptors_Overcommit_Memory.md
                  - Kafka Production Concerns: streaming/kafka/09-Kafka_Production_Concerns.md
                  - Kafka Message Types: streaming/kafka/10-Kafka_Message_Types.md
                  - Kafka Configuring Producers Pt1: streaming/kafka/11-Kafka_Configuring_Producers_Pt1.md
                  - Kafka Configuring Producers Pt2: streaming/kafka/12-Kafka_Configuring_Producers_Pt2.md
                  - Kafka Serializers Avro Pt1 : streaming/kafka/13-Kafka_Serializers_Avro_Pt1.md
                  - Kafka Serializers Avro Pt2 : streaming/kafka/14-Kafka_Serializers_Avro_Pt2.md
                  - Kafka Partitions : streaming/kafka/15-Kafka_Partitions.md
                  - Kafka Headers : streaming/kafka/16-Kafka_Headers.md
                  - Kafka Interceptors: streaming/kafka/17-Kafka_Interceptors.md
                  - Kafka Quotas and Throttling : streaming/kafka/18-Kafka_Quotas_And_Throttling.md
                  - Kafka Consumers Eager and Coorperative Rebalancing: streaming/kafka/19-Kafka_Consumer_Eager_And_Cooperative_Rebalance.md
                  - Kafka Consumer Static Partitioning: streaming/kafka/20-Kafka_Consumer_Static_Partitioning.md
                  - Kafka Poll Loop: streaming/kafka/21-Kafka_Poll_Loop.md
                  - Kafka Consumer Properties Part I : streaming/kafka/22-Kafka_Configuring_Consumers_Pt1.md
                  - Kafka Consumer Properties Part II : streaming/kafka/23-Kafka_Configuring_Consumers_Pt2.md
                  - Kafka Partition Assignment Strategies : streaming/kafka/24-Kafka_Partition_Assignment_Strategies.md
                  - Kafka Commits and Offsets: streaming/kafka/25-Kafka_Commits_Offsets_Intro.md
                  - Kafka Types of Commits: streaming/kafka/26-Kafka_Types_Of_Commits.md
                  - Kafka Rebalance Listeners: streaming/kafka/27-Kafka_Rebalance_Listeners.md
                  - Kafka Consuming Records with Specified Offset: streaming/kafka/28-Kafka_Consuming_Records_With_Spec_Offset.md
                  - Kafka Exiting Consumers and Poll Loop : streaming/kafka/29-Kafka_Exiting_Consumer_Poll_Loop.md
                  - Kafka Deserializers : streaming/kafka/30-Kafka_Deserialisers.md
                  - Kafka Standalone Consumers : streaming/kafka/31-Kafka_Standalone_Consumers.md
                  - Kafka Internals of Zookeeper : streaming/kafka/32-Kafka_Internals_Zookeeper.md
                  - Kafka Raft Consensus Protocol : streaming/kafka/33-Kafka_Raft_Consensus_Protocol.md
                  - Kafka Controller Quorum Concepts : streaming/kafka/34-Kafka_Controller_Quorum.md
                  - Kafka Replication Concepts: streaming/kafka/35-Kafka_Replication_Concepts.md
                  - Kafka Insync and Out Of Sync Replicas : streaming/kafka/36-Kafka_InSync_OutOfSync_Replicas.md
                  - Kafka Request Processing Introduction : streaming/kafka/37-Kafka_Request_Processing_Pt1.md
                  - Kafka Request Processing - Producer Requests : streaming/kafka/38-Kafka_Request_Processing_Pt2_Produce_Requests.md
                  - Kafka Request Processing - Fetch Requests Part 1 : streaming/kafka/39-Kafka_Fetch_Requests_Pt1.md
                  - Kafka Request Processing - Fetch Requests Part 2 : streaming/kafka/40-Kafka_Fetch_Requests_Pt2.md
                  - Kafka Physical Storage - Introduction : streaming/kafka/41-Kafka_Physical_Storage_Introduction.md
                  - Kafka Tiered Storage Concepts : streaming/kafka/42-Kafka_Tiered_Storage.md
                  - Kafka Partition Allocation Process : streaming/kafka/43-Kafka_Partition_Allocation.md
                  - Kafka File Formats Introduction : streaming/kafka/44-Kafka_File_Formats_Intro.md
                  - Kafka Message Batch Headers : streaming/kafka/45-Kafka_Message_Batch_Headers.md
  - Documentation Deep Dive:
      - Topics:
          - Databricks:
              - Topics:
                  - What is Lakehouse? : docs-deep-dive/databricks/00-What_Is_Lakehouse.md
                  - Lakehouse vs Delta Lake vs Warehouse : docs-deep-dive/databricks/01-Lakehouse_vs_Delta_Lake_vs_Warehouse.md
                  - All things Delta! : docs-deep-dive/databricks/02-All_Delta_Things_Databricks.md
                  - High Level Databricks Architecture: docs-deep-dive/databricks/03-High_Level_Architecture.md
                  - Databricks ACID Guarantees: docs-deep-dive/databricks/04-Databricks_ACID_Guarantees.md
                  - Medallion Design Pattern: docs-deep-dive/databricks/05-Databricks_Medallion_Architecture.md
                  - Databricks Single Source of Truth Architecture: docs-deep-dive/databricks/06-Databricks_Single_Source_Of_Truth_Arch.md
                  - Databricks Scope of Lakehouse Architecture: docs-deep-dive/databricks/07-Databricks_Scope_Of_Lakehouse_Arch.md
                  - Databricks Architectural Guiding Principles: docs-deep-dive/databricks/08-Databricks_Architecture_Guiding_Principles.md
                  
# END AUTO NAV
extra:
  navigation:
    previous: "‚Üê Previous"
    next: "Next ‚Üí"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vedanthv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vedanthvbaliga
  generator: false

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js

copyright: |
  &copy; 2023-2025 <a href="https://github.com/vedanthv" target="_blank" rel="noopener">Vedanth V Baliga</a>
